# Generated by Django 5.0 on 2024-01-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Reserve',
        ),
    ]
