# Generated by Django 5.0 on 2023-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salles',
            name='reservations',
            field=models.ManyToManyField(related_name='salles_set', to='User.reservations'),
        ),
    ]
